FROM python:3.10-slim AS trainer
WORKDIR /app
COPY requirements.txt .
COPY simple_nn.py .
RUN pip install --no-cache-dir -r requirements.txt
RUN python simple_nn.py
CMD ["cp", "mnist_model.h5", "/app/model/mnist_model.h5"]