
FROM python:3.10-slim AS inference
WORKDIR /app
COPY requirements.txt .
COPY app.py .
COPY model/mnist_model.h5 /app/
COPY templates /app/templates
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000
CMD ["python", "app.py"]