FROM python:3.10-slim
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*
RUN pip install pybind11 Flask
WORKDIR /app
COPY . .
RUN mkdir -p build && cd build && \
   cmake -DCMAKE_PREFIX_PATH=$(python -c "import pybind11; print(pybind11.get_cmake_dir())") .. && \
   make
RUN cp build/example.cpython-*-x86_64-linux-gnu.so ./

CMD ["python", "main.py"]