version: '3.9'

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - .:/app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - builder
    ports:
      - "5000:5000"
    volumes:
      - .:/app
